In [12]:
import pandas as pd
import json
import geopandas as gpd
import os

In [7]:
data = pd.read_csv(r'E:\Projects\National Anthems\data\national_anthems.csv')
data

,Country,Alpha-2,Alpha-3,Continent,Anthem
0,Albania,AL,ALB,Europe,"Around our flag we stand united, With one wish..."
1,Armenia,AM,ARM,Europe,"Our Fatherland, free, independent, That has fo..."
2,Austria,AT,AUT,Europe,"Land of mountains, land by the river, Land of ..."
3,Azerbaijan,AZ,AZE,Europe,"Azerbaijan, Azerbaijan! The glorious Fatherlan..."
4,Belarus,BY,BLR,Europe,"We, Belarusians, are peaceful people, Wholehea..."
...,...,...,...,...,...
185,Tunisia,TN,TUN,Africa,O defenders of the Homeland! Rally around to t...
186,Uganda,UG,UGA,Africa,"Oh Uganda! May God uphold Thee, We lay our fut..."
187,Western Sahara,EH,ESH,Africa,"O sons of the Sahara! In the battlefield, you ..."
188,Zambia,ZM,ZMB,Africa,"Stand and sing of Zambia, proud and free, Land..."
189,Zimbabwe,ZW,ZWE,Africa,"Oh lift high the banner, the flag of Zimbabwe ..."

In [8]:
data = data.iloc[:,[0,2]]

In [9]:
data

            Country Alpha-3
0           Albania     ALB
1           Armenia     ARM
2           Austria     AUT
3        Azerbaijan     AZE
4           Belarus     BLR
..              ...     ...
185         Tunisia     TUN
186          Uganda     UGA
187  Western Sahara     ESH
188          Zambia     ZMB
189        Zimbabwe     ZWE

[190 rows x 2 columns]

In [10]:
path = r'E:\Projects\National Anthems\data\world-countries.json'
country = json.load(open(path))
gfp = gpd.read_file(path)

In [11]:
gfp

,id,name,geometry
0,AFG,Afghanistan,"POLYGON ((61.21082 35.65007, 62.23065 35.27066..."
1,AGO,Angola,"MULTIPOLYGON (((16.32653 -5.87747, 16.57318 -6..."
2,ALB,Albania,"POLYGON ((20.59025 41.8554, 20.46318 41.51509,..."
3,ARE,United Arab Emirates,"POLYGON ((51.57952 24.2455, 51.75744 24.29407,..."
4,ARG,Argentina,"MULTIPOLYGON (((-65.5 -55.2, -66.45 -55.25, -6..."
...,...,...,...
172,PSE,West Bank,"POLYGON ((35.54566 32.39399, 35.54525 31.7825,..."
173,YEM,Yemen,"POLYGON ((53.10857 16.65105, 52.38521 16.38241..."
174,ZAF,South Africa,"POLYGON ((31.521 -29.25739, 31.32556 -29.40198..."
175,ZMB,Zambia,"POLYGON ((32.75938 -9.2306, 33.23139 -9.67672,..."
176,ZWE,Zimbabwe,"POLYGON ((31.19141 -22.25151, 30.65986 -22.151..."

In [37]:
def geomark(label_dir,geoplots_dir,data,gfp):
    for filename in os.listdir(label_dir):
        if filename.endswith('.csv'):
            filepath = os.path.join(label_dir,filename)
        labels = pd.read_csv(filepath)
        data['Label'] = labels['Label']
        merge = pd.merge(gfp,data,left_on='id',right_on='Alpha-3')
        geoplot = merge[['id','name','Label','geometry']]
        savepath = os.path.join(geoplots_dir,filename)
        geoplot.to_csv(savepath,index=False)

In [38]:
label_dir = r'E:\Projects\National Anthems\labels'
geoplot_dir = r'E:\Projects\National Anthems\data\geoplots'
data = pd.read_csv(r'E:\Projects\National Anthems\data\national_anthems.csv')

In [39]:
data

,Country,Alpha-2,Alpha-3,Continent,Anthem
0,Albania,AL,ALB,Europe,"Around our flag we stand united, With one wish..."
1,Armenia,AM,ARM,Europe,"Our Fatherland, free, independent, That has fo..."
2,Austria,AT,AUT,Europe,"Land of mountains, land by the river, Land of ..."
3,Azerbaijan,AZ,AZE,Europe,"Azerbaijan, Azerbaijan! The glorious Fatherlan..."
4,Belarus,BY,BLR,Europe,"We, Belarusians, are peaceful people, Wholehea..."
...,...,...,...,...,...
185,Tunisia,TN,TUN,Africa,O defenders of the Homeland! Rally around to t...
186,Uganda,UG,UGA,Africa,"Oh Uganda! May God uphold Thee, We lay our fut..."
187,Western Sahara,EH,ESH,Africa,"O sons of the Sahara! In the battlefield, you ..."
188,Zambia,ZM,ZMB,Africa,"Stand and sing of Zambia, proud and free, Land..."
189,Zimbabwe,ZW,ZWE,Africa,"Oh lift high the banner, the flag of Zimbabwe ..."

In [40]:
geomark(label_dir,geoplot_dir,data,gfp)